name: Deploy To Server

on:
  push:
    branches:
      - master
    paths:
      - 'Server/**'
      - '.github/workflows/serverDeployment.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t OpenMsgr-Server:latest ./Server

      - name: Save Docker Image
        run: |
          docker save OpenMsgr-Server:latest | gzip > OpenMsgr-Server.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenMsgrDockerImage
          path: OpenMsgr-Server.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: OpenMsgrDockerImage

      - name: Upload Docker Image to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: OpenMsgr-Server.tar.gz
          target: OpenMsgr/tmp/OpenMsgr-Server.tar.gz

      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/OpenMsgr/tmp/
            mkdir -p ~/OpenMsgr/tmp/
            echo "Killing and Removing Old Container"
            docker kill OpenMsgr-Server || true
            docker rm OpenMsgr-Server || true

            echo "Loading Docker Image"
            cd ~/OpenMsgr/tmp/
            gunzip -c OpenMsgr-Server.tar.gz | docker load

            echo "Running Docker Container"
            docker run -d --name OpenMsgr-Server -p 5000:5000 OpenMsgr-Server:latest
