name: Deploy To Server 

on:
  push:
    branches:
      - master

    paths:
      - 'Server/**'
      - '.github/workflows/serverDeployment.yml'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up Previous Instance
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/OpenMsgr/tmp/
            echo "Killing possible existing openmsgr-server container"
            docker kill openmsgr-server || true
            echo "Removing possible existing openmsgr-server container"
            docker rm openmsgr-server || true

            mkdir -p ~/OpenMsgr/tmp/


      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t openmsgr-server:latest ./Server
      
      - name: Save Docker Image
        run: |
          docker save openmsgr-server:latest | gzip > openmsgr-server.tar.gz

      - name: Upload Docker Image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: openmsgr-server.tar.gz
          target: OpenMsgr/tmp/openmsgr-server.tar.gz

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd OpenMsgr/tmp/
            echo "Loading Docker Image"
            gzip -d openmsgr-server.tar.gz < openmsgr-server.tar.gz | docker load
            docker run -d --name openmsgr-server -p 5000:5000 openmsgr-server:latest
