name: Deploy To Server

on:
  push:
    branches:
      - Master

    paths:
      - 'Server/**'
      - '.github/workflows/serverDeployment.yml'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up Prevous Instance
        uses: appleboy:ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/OpenMsgr/tmp/
            echo "Killing posible existing OpenMsgr-Server container"
            docker kill OpenMsgr-Server || true
            echo "Removing possible existing OpenMsgr-Server container"
            docker rm OpenMsgr-Server || true

            mkdir -p ~/OpenMsgr/tmp/


      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t OpenMsgr-Server:latest ./Server
      
      - name: Save Docker Image
        run: |
          docker save OpenMsgr-Server:latest | gzip > OpenMsgr-Server.tar.gz

      - name: Upload Docker Image
        uses: appleboy:scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: OpenMsgr-Server.tar.gz
          target: OpenMsgr/tmp/OpenMsgr-Server.tar.gz

      - name: SSH to Server and Deploy
        uses: appleboy:ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd OpenMsgr/tmp/
            echo "Loading Docker Image"
            gzip -d OpenMsgr-Server.tar.gz | docker load 
            docker run -d --name OpenMsgr-Server -p 5000:5000 OpenMsgr-Server:latest

            
